name: redis-starter-python
services:
  redis:
    container_name: redis
    image: "redis:alpine"
    ports:
      - 6379:6379
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - redis-data:/data

  server:
    container_name: server
    build: .
    ports:
      - "${PORT-8080}:${PORT-8080}"
    environment:
      PORT: ${PORT-8080}
    env_file:
      - .env
      - .env.docker
    restart: always
    depends_on:
      - redis

volumes:
  redis-data:
